### ISSUE TITLE
Upgrading to 3.0.0 and application crashes

### ISSUE THREAD

**Issue by xantari** [datalust/seq-app-firstoftype#1]
Upgraded to 3.0.0 and received the following crashes.

Running Seq version 2020.3.4761

![image](https://user-images.githubusercontent.com/6610039/124121877-0cf15400-da3b-11eb-8ea6-4d0a7f358f92.png)

![image](https://user-images.githubusercontent.com/6610039/124121922-167abc00-da3b-11eb-8790-b23732ad68ca.png)

**Comment by xantari** [comment]
Interesting, so I tried restarting the Seq service and that seems to make it not crash anymore after I did a restart. Still monitoring to see if it crashes again.

**Comment by nblumhardt** [comment]
Thanks for the heads-up, @xantari ; I think this one is:

https://github.com/datalust/seq-tickets/issues/1242
