### ISSUE TITLE
Project site on nuget links to incorrect github repo

### ISSUE THREAD

**Issue by xantari** [datalust/seq-app-firstoftype#2]
The nuget.org site for this package: https://www.nuget.org/packages/Seq.App.FirstOfType/

When clicking on "Project Site", it goes to the HTML email plugin instead of this one.

**Comment by nblumhardt** [comment]
Thanks! Should be fixed shortly 👍

**Comment by GWeidmann** [comment]
Still goes to the wrong page

**Comment by nblumhardt** [comment]
Thanks @GWeidmann I'll take another look!

**Comment by nblumhardt** [comment]
The fix for this was merged, but the build isn't hooked up (it's a slooooow moving package). Taking a look at that now.

**Comment by nblumhardt** [comment]
New package published; should be visible on NuGet shortly. Thanks again!

**Comment by xantari** [comment]
Confirmed. Closing.
