### ISSUE TITLE
Cannot find first of type messages

### ISSUE THREAD

**Issue by THammond9** [datalust/seq-app-firstoftype#4]
Not sure if I am missing something but I cannot seem to find the output in the stream. The app seems to be doing something though.
![image](https://github.com/datalust/seq-app-firstoftype/assets/18351046/31825455-4f1e-4b96-9934-38bebdd3e496)

There is nothing in the diagnostic events filter. I also searched for "First of" and the only results are logs from our application.

Where could I look to diagnose the problem and/or see the out put of this app?

**Comment by liammclennan** [comment]
It looks like you are streaming all new events to the First of Type app. If an event arrives with a message template that has not been seen before it should generate a new event in the log. 

You can try generating a log event with a novel message template using seqcli: https://docs.datalust.co/docs/seqcli

**Comment by THammond9** [comment]
It seems there was an incompatibility with our older 5.1 (I think) version of Seq. We updated and First of type works.

**Comment by liammclennan** [comment]
@THammond9 that's great. Also 2023.2 is way better.
